const{ Telegraf } = require('telegraf')
const dotenv=require('dotenv')
dotenv.config()
const bot=new Telegraf(process.env.APIKEY)
bot.start((ctx)=>(ctx.reply('Welcome to the bot')))
bot.command('kle',(ctx)=>(ctx.reply('kle offers bca')))
bot.command('link',(ctx)=>(ctx.replyWithHTML(`<a href="http://www.klescpdds.edu.in/">Link</a>`)))
bot.command('location',(ctx)=>(ctx.replyWithLocation(16.386,75.114)))
bot.command('meme',async(ctx)=>{await ctx.replyWithAnimation('https://media.tenor.com/aCNInP825lEAAAAi/2026-happy-new-year.gif')})
bot.launch()